### ISSUE TITLE
AttributeError: 'ComputeSession' object has no attribute 'id'

### ISSUE THREAD

**Issue by rlatjcj** [lablup/backend.ai#219] opened 2020-09-08 18:09 UTC
**Describe the bug**
After removing no longer needed argument when using `client.request.Request` instances, `AttributeError: 'ComputeSession' object has no attribute 'id'` was occured in `src/ai/backend/client/versioning.py:33` with the command, `backend.ai app ID jupyterlab`.
```
def get_id_or_name(api_version: Tuple[int, str], obj: ComputeSession) -> str:
    if api_version[0] <= 4:
        return obj.name
    return obj.id
```

**To Reproduce**
1. [branch for PR in backend.ai-client-py](https://github.com/lablup/backend.ai-client-py/pull/128)
2. manager and agent was on.
3. In client, new container was started with any images and app, e.g. jupyter lab, was run in the container.

**Expected behavior**
Apps, e.g. jupyter lab, will be running.

**Screenshots**
![image](https://user-images.githubusercontent.com/33727805/92511484-540e1e80-f248-11ea-966d-3a1edf3f843d.png)

**Client:**
 - OS: Ubuntu 18.04
 - Python version: 3.8.3
 - NodeJS version: 13.14.0

**Server:**
 - OS: Ubuntu 18.04
 - Backend.AI version: 20.09.0a1.dev0
 - Python version: 3.8.3
 - Installation method: used scripts/install-dev.sh

**Additional context**
As shown in the picture above, the variable `api_version[0]` was printed `6`, but `ComputeSession` had no attribute `'id'`. When the version check was removed, it worked normally again. Should the version check be removed from the source code?

**Comment by rlatjcj** [comment] 2020-09-09 01:00
In master branch with same environments, same issue was occured, too.

**Comment by inureyes** [comment] 2020-09-14 13:12
@yongkyunlee please check whether it reproduces or not. We just changed every sessionName-based calls to use UUID.

**Comment by yongkyunlee** [comment] 2020-09-16 10:14
@inureyes The problem is reproduced for me as well. I will take a look.

**Comment by achimnol** [comment] 2022-07-18 04:40
Closing as it has no activities more than 20 months.

**Closed by achimnol** 2022-07-18 04:40 UTC
Labels: bug
