### ISSUE TITLE
Let's provide API for changing vfolder ownership(`user` attribute)

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai#1070] opened 2023-02-18 07:52 UTC
### Main idea

For now, we only support create / share / revoke-sharing, but don't support changing the "user" yet.
In certain situations, users may want to delegate the ownership of the vfolder that they created by themselves.
Let's implement this feature so that we can provide enhanced data mgmt.

There are two ownership types(user, (project) group) in the current system of vfolder.
changing a vfolder ownership should be treated respectively since the characteristic of the vfolder is different.
But we need to follow this condition ("Change `user` field, not `creator` field in vfolder"), regardless of the ownership type.

- Changing the ownership of the "user" vfolder
   - When new-owner is previously "shared" one, then corresponding record in `vfolder_permissions` table will be deleted.
- Changing the ownership of "project" vfolder
   - When changing the `user`, all of the related records in `vfolder_permissions` will be deleted.

**Comment by achimnol** [comment] 2023-02-21 02:10
Duplicate of #408.

**Closed by achimnol** 2023-02-21 02:10 UTC
Labels: feature, manager, enhance
