### ISSUE TITLE
Cannot execute session using GPU resource in 23.03.0dev0 Version

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai#1058] opened 2023-02-16 00:36 UTC
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

23.03.0dev0

### Describe the bug

After updating Backend.AI Cluster version to the latest, when it comes to creating session with GPU resource (e.g. using TF 2.7 image, etc.) agent process throws `TypeError: 'CancelledError' object is not subscriptable` and the status of session goes from `PREPARING` to `CANCELLED`. Unlikely this case, when I try to execute session with image that doesn't need GPU resource(e.g. Python 3.9), session works fine. It happens always and I think this is a critical issue.
Here's the error log that I got right after creating session with GPU resource.

### Screenshot(s)
<img width="1413" alt="Screenshot 2023-02-16 at 9 30 03 AM" src="https://user-images.githubusercontent.com/46954439/219227660-8246ae72-c318-48da-8cf5-1fe6f505d41b.png">

### To Reproduce

Create a session with GPU resource using an image that requires/supports GPU resource. (e.g. TF 2.7, 2.5, PyTorch 1.7...)

### Expected Behavior

Users can run session regardless of the resource they want to allocate (though they cannot create a single session that off the limit.)

```[tasklist]
### Tasks
- [ ] #956
- [ ] #1081
```

**Comment by achimnol** [comment] 2023-02-16 07:57
- We need to handle `CancelledError` passed as `result` more gracefully.
- Need to know why it's cancelled in the first place.

**Comment by lizable** [comment] 2023-02-21 02:24
@achimnol @kyujin-cho I found that It happens not only in WebUI but also in CLI.

Here are the screenshots when I try to create a session using GPU resources.

### Screenshot(s)
* Result of executing session creation request via CLI
<img width="1297" alt="Screenshot 2023-02-21 at 11 20 08 AM" src="https://user-images.githubusercontent.com/46954439/220231275-705d18d1-6f06-443d-bcc1-6982bce243e6.png">

* manager process log after creating session
<img width="1862" alt="Screenshot 2023-02-21 at 11 20 20 AM" src="https://user-images.githubusercontent.com/46954439/220231339-47c0c636-5e0d-4a42-9f70-c8ea929eb7df.png">

* agent process log after creating session.
Got the same result from [here]()https://github.com/lablup/backend.ai/issues/1058#issue-1586805607.

**Comment by achimnol** [comment] 2023-02-21 05:29
@kyujin-cho has figured out the root cause: this issue could be fixed by #956.
When there are newer versions of distro-specific binaries, the current `match_distro()` algorithm chooses the latest ones and then the session's krunner crashes with missing glibc symbols, causing unexpected exceptions after creating the container and mishandling of such in-mid exceptions while waiting for the krunner to become ready.

**Comment by achimnol** [comment] 2023-02-21 05:30
So, @kyujin-cho will work on #956, and @fregataa will work on fixing the exception mishandling.

**Closed** 2023-02-24 09:25 UTC
Labels: bug, blocker, agent

**Comment by lizable** [comment] 2023-02-27 02:56
@achimnol @kyujin-cho @fregataa 
It happens again in this PR #1115.
