### ISSUE TITLE
Bug: vfolder mounted running session can be removed

### ISSUE THREAD

**Issue by gee05053** [lablup/backend.ai#1410] opened 2023-07-22 08:10 UTC
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

23.09.0-alpha2

### Describe the bug
![스크린샷 2023-07-22 17-13-58](https://github.com/lablup/backend.ai/assets/28584221/2bd2eae2-f029-49b6-a322-59c9bb3db42b)
![스크린샷 2023-07-22 17-16-24](https://github.com/lablup/backend.ai/assets/28584221/04f25f6f-8e7e-49a4-8c1b-862c92358135)

vfolder mounted running session can remove

### To Reproduce

1. create new a vfolder
2. create new session and mount vfolder
3. vfolder mounted running session remove

### Expected Behavior

vfolder mounted running session can't remove and popup error message
ex) Can't remove the vfolder mounted running session

**Comment by achimnol** [comment] 2023-07-23 07:12
Thanks for the report. It's a duplicate of #776. Let's resolve the issue there.

**Closed by achimnol** 2023-07-23 07:12 UTC
Labels: type:bug
