### ISSUE TITLE
VFolder not found when starting new session.

### ISSUE THREAD

**Issue by DoyunShin** [lablup/backend.ai#1416] opened 2023-07-25 03:54 UTC
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

23.03.9

### Describe the bug

![image](https://github.com/lablup/backend.ai/assets/60532811/8f83f8b5-a139-4a92-bb60-8ba5f9d64525)
![image](https://github.com/lablup/backend.ai/assets/60532811/6e1fd20f-0c27-41d9-8d70-cfc971b2ccf0)

While the automount folder is being deleted, I can't create any new session.
The error shows "VFolder not found".

### To Reproduce

1. While the automount storage status is "deleting"
2. create a new session

### Expected Behavior

Instant successfully created.

### Anything else?

I tried in backend ai cloud. If assignee has permission to see cloud logs, then you can search with "op@doyun.me".

**Comment by achimnol** [comment] 2023-07-27 10:23
We are going to improve the check for vfolder mounts on existing (non-terminated) sessions when deleting a vfolder.

**Comment by achimnol** [comment] 2023-07-27 10:24
This is actually a well-know issue hanging for a long time — duplicate of #776.

**Closed** 2023-07-27 10:25 UTC
Labels: type:bug
